apiVersion: v1
kind: Service
metadata:
  name: mongodemo
  labels:
    app: camongodemose
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: LoadBalancer
  selector:
    app: mongodemo
